---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kyma
  labels:
    app: hello-kyma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kyma
  template:
    metadata:
      labels:
        app: hello-kyma
    spec:
      containers:
      - name: hello-kyma
        image: ghcr.io/sap-samples/kyma-runtime-learning-journey/hello-kyma:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
          requests:
            memory: 32Mi
            cpu: 10m
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-kyma
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  labels:
    app: hello-kyma
spec:
  selector:
    app: hello-kyma
  ports:
  - name: http
    port: 8080
    protocol: TCP
