apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: hello-world-function
  labels:
    app: hello-world-function
spec:
  runtime: nodejs20
  source: 
    inline:
      dependencies: |
        { 
          "name": "hello-world-function",
          "version": "1.0.0",
          "dependencies": {}
        } 
      source: |-
        module.exports = {
            main: async function (event, context) {
              const message = `Hello ` + process.env.NAME
                + ` from the Kyma Function ${context["function-name"]}`
                + ` running on ${context.runtime}!`;
              console.log(message);
              return message;
            }
          } 
  env:
    - name: NAME
      value: "Kyma"